param storedKeyId string

//TODO: Add autogenerate public key logic
/*
resource autogenerate_publickey 'Microsoft.Compute/sshPublicKeys@2023-09-01' = if (autogenerateSecrets) {
  name: 'autoGeneratedKey'
  location: location
}
*/
resource stored_publickey 'Microsoft.Compute/sshPublicKeys@2025-04-01' existing = {
  name: split(storedKeyId, '/')[8]
  scope: resourceGroup(split(storedKeyId,'/')[4])
}

output publicKey string = stored_publickey.properties.publicKey
